"""upgrade vendor quotations to header + line items

Revision ID: 952a8a89455f
Revises: f605386a0a29
Create Date: 2026-03-09 15:05:48.055687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952a8a89455f'
down_revision: Union[str, None] = 'f605386a0a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['vendor_quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.add_column('vendor_quotations', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('vendor_quotations', sa.Column('gst_total', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('vendor_quotations', sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('vendor_quotations', sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.drop_column('vendor_quotations', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_quotations', sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_column('vendor_quotations', 'grand_total')
    op.drop_column('vendor_quotations', 'discount')
    op.drop_column('vendor_quotations', 'gst_total')
    op.drop_column('vendor_quotations', 'subtotal')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    # ### end Alembic commands ###
